### ISSUE TITLE
debug sections seem to be unhandled?

### ISSUE THREAD

**Issue by roboknight** [LongSoft/TE2PE#2]
I am trying to convert a TE file into a PE file and get:
convert: unknown section ".debug" found in TE image.

I have a file that contains the debug section.  I'll attach it if I can.  I suspect it is a "quick" fix, but I'm not familiar enough with the TE sections to create a fix.

**Comment by vit9696** [comment]
It is unknown as in can contain anything. It is handled as is and does not cause issues to file generation.
